export {
  View,
  Text,
  TextProps,
  TextInputProps,
  TouchableOpacity,
  TouchableOpacityProps,
  TouchableWithoutFeedback,
  Keyboard,
  TextInput,
  Image,
  KeyboardAvoidingView,
  ScrollView,
  Platform,
} from "react-native";
